#!/bin/bash

# Esposito OS - Boot Log Analyzer
# Use this to analyze serial output during boot

echo "Esposito OS - Boot Log Analyzer"
echo "================================"
echo ""
echo "Connect to serial monitor and boot the device."
echo "Look for the following boot sequence markers:"
echo ""

echo "EXPECTED BOOT OUTPUT:"
echo "─────────────────────────────────────────────"
echo "I (xxx) esposito: Esposito OS v0.1.0-alpha"
echo "I (xxx) esposito: Starting boot sequence..."
echo "I (xxx) boot: ╔═══════════════════════════════════════╗"
echo "I (xxx) boot: ║     Esposito OS Boot Sequence        ║"
echo "I (xxx) boot: ║     ESP32 CYD (2USB version)         ║"
echo "I (xxx) boot: ╚═══════════════════════════════════════╝"
echo "I (xxx) boot: ✓ Display Init"
echo "I (xxx) boot:   Display ready"
echo "I (xxx) boot: ✓ Hardware Init"
echo "I (xxx) boot:   Hardware ready"
echo "I (xxx) boot: ✓ Filesystem Init"
echo "I (xxx) boot:   Filesystem ready"
echo "I (xxx) boot: ✓ Keyboard Init"
echo "I (xxx) boot:   Keyboard subsystem ready"
echo "I (xxx) boot: ✓ App Loader Init"
echo "I (xxx) boot:   App loader ready"
echo "I (xxx) boot: ✓ Load Default App"
echo "I (xxx) boot: ╔═══════════════════════════════════════╗"
echo "I (xxx) boot: ║     BOOT SEQUENCE COMPLETE            ║"
echo "I (xxx) boot: ╚═══════════════════════════════════════╝"
echo "I (xxx) boot: ✓ System ready"
echo "I (xxx) esposito: Starting main event loop..."
echo "─────────────────────────────────────────────"
echo ""

echo "COMMON ISSUES TO LOOK FOR:"
echo "─────────────────────────────────────────────"
echo "✗ Display Init - Display not available"
echo "  → SPI communication failed, check wiring"
echo ""
echo "✗ Hardware Init - Hardware initialization failed"
echo "  → Check hardware_config.h pin definitions"
echo ""
echo "✗ Filesystem Init - Filesystem initialization failed"
echo "  → SPIFFS partition not found or corrupted"
echo ""
echo "✗ Keyboard Init - Keyboard not detected"
echo "  → BBQ20 keyboard not connected, I2C scan failed"
echo "  → This is non-fatal, system continues"
echo "─────────────────────────────────────────────"
echo ""

echo "TO CAPTURE BOOT LOG:"
echo "1. Connect device via USB"
echo "2. Run: idf.py monitor"
echo "3. Reset device or run: idf.py flash monitor"
echo "4. Copy the output and paste here for analysis"
echo ""

echo "QUICK TEST COMMANDS:"
echo "  idf.py menuconfig    - Configure project"
echo "  idf.py build         - Build project"
echo "  idf.py flash         - Flash to device"
echo "  idf.py monitor       - Open serial monitor"
echo "  idf.py flash monitor - Flash and monitor in one command"
echo ""
