#ifndef HARDWARE_CONFIG_H
#define HARDWARE_CONFIG_H

#include "board.h"

#define SCREEN_WIDTH BOARD_SCREEN_WIDTH
#define SCREEN_HEIGHT BOARD_SCREEN_HEIGHT
#define DEFAULT_DISPLAY_ROTATION BOARD_DEFAULT_DISPLAY_ROTATION

#define COLOR_BLACK 0x0000
#define COLOR_WHITE 0xFFFF
#define COLOR_RED 0xF800
#define COLOR_GREEN 0x07E0
#define COLOR_BLUE 0x001F
#define COLOR_YELLOW 0xFFE0

// Touch interrupt GPIO used for light sleep wakeup (name varies by board)
#if defined(BOARD_TOUCH_IRQ)
#define BOARD_TOUCH_WAKE_GPIO BOARD_TOUCH_IRQ
#elif defined(BOARD_TOUCH_INT)
#define BOARD_TOUCH_WAKE_GPIO BOARD_TOUCH_INT
#endif

#endif // HARDWARE_CONFIG_H
