#ifndef BOARD_CYD_2USB_H
#define BOARD_CYD_2USB_H

#define BOARD_NAME "CYD 2USB"

// Display
#define BOARD_SCREEN_WIDTH 320
#define BOARD_SCREEN_HEIGHT 240
#define BOARD_DEFAULT_DISPLAY_ROTATION 1
#define BOARD_DISPLAY_TYPE_ST7789

// Display SPI Pins
#define BOARD_LCD_SPI_HOST SPI2_HOST
#define BOARD_LCD_SCLK 14
#define BOARD_LCD_MOSI 13
#define BOARD_LCD_MISO 12
#define BOARD_LCD_DC 2
#define BOARD_LCD_CS 15
#define BOARD_LCD_BL 21

// Touchscreen (XPT2046 resistive touch)
#define BOARD_HAS_TOUCHSCREEN 1
#define BOARD_TOUCH_MOSI 32
#define BOARD_TOUCH_MISO 39
#define BOARD_TOUCH_CLK 25
#define BOARD_TOUCH_CS 33
#define BOARD_TOUCH_IRQ 36

#define BOARD_TOUCH_RAW_X_MIN 210
#define BOARD_TOUCH_RAW_X_RANGE 3600
#define BOARD_TOUCH_RAW_Y_MIN 260
#define BOARD_TOUCH_RAW_Y_RANGE 3600

// I2C Configuration for BBQ20 Keyboard
#define BOARD_I2C_SDA 22
#define BOARD_I2C_SCL 27
#define BOARD_I2C_PORT I2C_NUM_0
#define BOARD_I2C_FREQ 100000

// Keyboard
#define BOARD_HAS_BBQ20_KEYBOARD 1
#define BOARD_HAS_KEYBOARD_BACKLIGHT 1

// SD Card (VSPI bus, separate from display)
#define BOARD_HAS_SD_CARD 1
#define BOARD_SD_SPI_HOST SPI3_HOST
#define BOARD_SD_MISO_PIN 19
#define BOARD_SD_MOSI_PIN 23
#define BOARD_SD_CLK_PIN 18
#define BOARD_SD_CS_PIN 5

// RGB LED (discrete R/G/B LEDs via LEDC PWM)
#define BOARD_LED_RED_PIN 4
#define BOARD_LED_GREEN_PIN 16
#define BOARD_LED_BLUE_PIN 17
#define BOARD_LED_LEDC_TIMER LEDC_TIMER_0
#define BOARD_LED_LEDC_MODE LEDC_HIGH_SPEED_MODE
#define BOARD_LED_RESOLUTION LEDC_TIMER_8_BIT
#define BOARD_LED_FREQ 5000
#define BOARD_LED_CH_RED LEDC_CHANNEL_0
#define BOARD_LED_CH_GREEN LEDC_CHANNEL_1
#define BOARD_LED_CH_BLUE LEDC_CHANNEL_2

// Boot button
#define BOARD_BOOT_BUTTON_GPIO GPIO_NUM_0

#endif // BOARD_CYD_2USB_H
